services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: riwi_medicare
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: secret_key
      JWT_EXPIRES_IN: 1d
    depends_on:
      - postgres
    networks:
      - medicare-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: riwi_medicare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - medicare-network

volumes:
  postgres_data:

networks:
  medicare-network:
    driver: bridge